name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install IPFS CLI
        run: |
          curl -LO https://github.com/ipfs/kubo/releases/download/v0.18.0/kubo_v0.18.0_linux-amd64.tar.gz
          tar -xvzf kubo_v0.18.0_linux-amd64.tar.gz
          sudo mv kubo/ipfs /usr/local/bin/

      - name: Initialize and Start IPFS Daemon
        run: |
          ipfs init
          ipfs daemon &
          sleep 10

      - name: Add Files to IPFS
        run: |
          CID=$(ipfs add -r -Q ./)
          echo "Website CID: $CID"

      - name: Pin to Pinata
        run: |
          curl -X POST "https://api.pinata.cloud/pinning/pinByHash" \
          -H "Content-Type: application/json" \
          -H "pinata_api_key: ${{ secrets.PINATA_API_KEY }}" \
          -H "pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}" \
          --data "{\"hashToPin\":\"$CID\"}"
